[profile.default]
src = "src"
out = "out"
libs = ["lib"]
viaIR = true
solc_optimize = true
solc_via_ir = true
solc_optimize_runs = 200
remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    '@foundry-devops=lib/foundry-devops/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
]
# File system access for scripts (forge-std's VM.readFile/writeJson, etc.)
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "write", path = "./broadcast" },
    { access = "read", path = "broadcast" },
    { access = "write", path = "broadcast" },
    { access = "read", path = "./reports" },
    { access = "read", path = "./img/" },
    { access = "read", path = "./deployments" },
    { access = "write", path = "./deployments" },
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[lint]
exclude_lints = [
    "asm-keccak256",
    "unaliased-plain-import",
    "mixed-case-function",
    "mixed-case-variable",
    "pascal-case-struct",
]

[profile.coverage]
src = "src"
test = "test"
libs = ["lib"]
# Use minimal IR only when necessary from CLI (--ir-minimum) to avoid mapping skew.
fs_permissions = [{ access = "read", path = "./broadcast" }]
exclude = [
    "script/**",
    "tools/zk-circuits/build/**",
    "src/**/dependencies/**",
    "src/privacy_cross-chain/dependencies/**",
    "src/verification/dependencies/**",
    "src/organizations/dependencies/**",
]
