#!/usr/bin/env bash
set -euo pipefail

# Copies generated Solidity verifiers into the project under src/verification/verifiers
# WARNING: snarkjs names groth16 contract as `Groth16Verifier` in every file.
# Having multiple files with the same contract name in src will cause compile conflicts.
# Use this script ONLY if you plan to keep ONE verifier in src at a time,
# or you rename contract classes manually after copying.

ROOT_DIR="$(git rev-parse --show-toplevel 2>/dev/null || echo $(cd ../../.. && pwd))"
BUILD_DIR="$(cd "$(dirname "$0")/.." && pwd)/build"
TARGET_DIR="$ROOT_DIR/src/verification/verifiers"

mkdir -p "$TARGET_DIR"

declare -a FILES=(
  "AgeVerifier.sol"
  "AgeMaxVerifier.sol"
  "AttrVerifier.sol"
  "IncomeVerifier.sol"
)

echo "Copying verifiers from $BUILD_DIR to $TARGET_DIR"
for f in "${FILES[@]}"; do
  if [[ -f "$BUILD_DIR/$f" ]]; then
    cp "$BUILD_DIR/$f" "$TARGET_DIR/$f"
    echo "✅ Copied $f"
  else
    echo "⚠️  Skipped $f (not found). Run 'make verifiers' first."
  fi
done

cat << 'EOF'

NOTE:
- Solidity Groth16 verifiers generated by snarkjs all define `contract Groth16Verifier`.
- If you copy more than one into src, Foundry will fail due to duplicate contract names.
- Prefer deploying directly from tools/zk-circuits/build using forge create path:ContractName, e.g.:
    forge create --rpc-url $RPC_URL --private-key $PRIVATE_KEY \
      tools/zk-circuits/build/AgeVerifier.sol:Groth16Verifier

EOF
