// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/// @notice Interface for Groth16 verifier contracts generated by snarkjs
interface IGroth16Verifier {
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[] calldata publicSignals
    ) external view returns (bool);
}
